language: python
python:
  - 2.4
  - 2.6
  - 2.7
  - pypy
  - 3.1
  - 3.2
  - 3.3
  - 3.4
env:
    - DJANGO_VERSION=1.5.10 SAMPLE_PROJECT=sample_project
    - DJANGO_VERSION=1.6.7 SAMPLE_PROJECT=sample_project
    - DJANGO_VERSION=1.7.7 SAMPLE_PROJECT=sample_project
    - DJANGO_VERSION=1.8.3 SAMPLE_PROJECT=sample_project

branches:
    only:
        - master
install: python setup.py install
script: python setup.py test
